version: '2'
services:
  redis-cluster:
    environment:
     IP: ${REDIS_CLUSTER_IP}
    build:
      context: .
      args:
        redis_version: '4.0.9'
    hostname: server
    ports:
      - '30001-30006:30001-30006'
      - '6379:6379'
